require("andrew.plugins-setup")
require("andrew.core.options")
require("andrew.core.keymaps")
require("andrew.core.colorscheme")
require("andrew.plugins.nvim-tree")
require("andrew.plugins.lualine")
require("andrew.plugins.telescope")
require("andrew.plugins.nordic")
